avail_zone           = "eu-west-3b"
vpc_cider_block      = "10.0.0.0/16"
subnet_cider_block   = "10.0.100.0/24"
env_prefix           = "dev"
my_ip                = "0.0.0.0/0"
instance_type        = "t2.micro"
public_key_location  = "/Users/shlo/.ssh/id_rsa.pub"
private_key_location = "/Users/shlo/.ssh/id_rsa"